### ISSUE TITLE
Re-calculate textarea height on window resize

### ISSUE THREAD

**Issue by deathg0d** [devstark-com/vue-textarea-autosize#17]
This plugin does not fix height on window resize. (Ex. going from portrait mode to landscape mode on mobile phones, or simply resizing the browser window in pcs). Is there a way to manually trigger textarea resize calculations? Of course it would be great to have this feature built into the plugin. If it is going to be inbuilt the following considerations would be necessary: When you resize a browser window with mouse drag, it triggers window resize event many many time (hundreds). Calculating for all of these would be pretty bad so we could wait for the resize event to finish with timeout and re-calculate the textarea heights at the end.

**Comment by cliffordh** [comment]
Any luck with this? I am pretty close to finding a solution binding the min-height and max-height to a data property. 

`created() {
    window.addEventListener("resize", this.availableHeight);
  },
mounted() {
    this.availableHeight(); // force initialization of availableHeight
  },
destroyed() {
    window.removeEventListener("resize", this.availableHeight);
  },
methods: {
    availableHeight() {
        this.editorHeight =200;
}` 
          
The height gets recalculated (formula hardcoded to 200 right now). But the height of the control is not updated, unless I change tabs, reload or something.

**Comment by Saymon-biz** [comment]
@deathg0d 
1) actually, @cliffordh has picked the right way - to manage that via props, but that was impossible since `minHeight` and `maxHeight` props were not watched so they were not reactive. Now it became possible but you still have to implement the resize event handler in order to manage values of states bound to these props in a parent component since there is no universal rule that satisfies all possible cases so we have no something we can rely on in order to calculate exact values for different screen sizes.
2) regarding the way to trigger resize manually - you can use the `resize()` method which is accessible e.g. via ref: `this.$refs.myTextarea.resize()` and don't forget to add the ref itself: `<textarea-autosize ref="myTextarea" />`
3) regarding the idea to wait for the resize event finished - the right way is to make your event handler debounced using for instance https://www.npmjs.com/package/debounce
