### ISSUE TITLE
initial textarea height

### ISSUE THREAD

**Issue by AlexanderZanin** [devstark-com/vue-textarea-autosize#8]
Hello!
I have the problem with textarea height.

I have this template: 
<img width="371" alt="screen shot 2018-03-29 at 16 29 01" src="https://user-images.githubusercontent.com/10371454/38091477-54b350f8-336e-11e8-9690-d8cb3b478f30.png">

But textarea real height is 107px:
<img width="1311" alt="screen shot 2018-03-29 at 16 25 49" src="https://user-images.githubusercontent.com/10371454/38091350-fcd18bb6-336d-11e8-9903-5f504ce156e4.png">

And when I change CSS padding property then textarea changes its height.
Is it possible to prevent initial textarea height changing?

Or is it possible to set initial height of textarea?

**Comment by sejr** [comment]
I am having this same issue. @AlexanderZanin  did you happen to figure out a fix?

**Comment by AlexanderZanin** [comment]
@sejr , unfortunately no. I decided to use this plugin: http://www.jacklmoore.com/autosize/

If you want to use it too you need to add the ref attribute to your textarea inside the template:
`<textarea ref="textarea"></textarea>`
And then call the autosize function inside mounted vue lifecycle hook. Something like that: 
<img width="562" alt="screen shot 2018-05-23 at 11 05 24" src="https://user-images.githubusercontent.com/10371454/40411488-453d497c-5e79-11e8-84ae-09e426a56435.png">

**Comment by sundbox** [comment]
Followed instructions by @AlexanderZanin and works fine.

In my case y have multiple textareas and works, but when I create a new one on the fly the new textarea don't have autosize function, so in my case I put the code in the `updated()` function instead of `mounted()`.

To be more specific think in the typical Tasks App example, one textarea for each task, so there's a "New Task" button that adds an empty task to the 'tasks' array.
All the tasks loaded before mounted will have autosize function, but not the new ones if your code is inside `mounted()`, but all works if put inside `updated()`.

My final code looks like this:
```
updated() {
    const textareas = this.$refs.textarea;
    autosize(textarea);
},
```
Very grateful to @AlexanderZanin you saved me a lot of time obsessed with this aesthetic nonsense and I think is fair wasting some time writing this comment to help others.

**Comment by Saymon-biz** [comment]
@AlexanderZanin you can disable/enable auto sizing just by providing `autosize` property with `false` or `true` value. In other words, you can set prop `autosize` initially to `false` and then set `true` when it becomes necessary. There are no any other ways to set initial height right now. Also feel free to send pull requests, it's the fastest way to get desired behavior

**Comment by xelblch** [comment]
If you guys tried to add rows="1" to your <textarea-autosize>? It will render textarea with only single row and not auto-expand it. Works perfect for me.

**Comment by franciscolourenco** [comment]
This is worthwhile to document in the readme.

**Comment by Saymon-biz** [comment]
> This is worthwhile to document in the readme.

That's a great idea! will update soon
